# ==============================================================
# = Articoli Web Service - Versione Base
# ==============================================================

server:
  port: 5051

spring:
  application:
    name: ProductsWebService
# ==============================================================
# = DBMS PostgreSQL Parameters
# ==============================================================
  datasource:
    initialization-mode: always
    password: 123_Stella
    platform: postgres
    url: jdbc:postgresql://localhost:5433/AlphaShop
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
    

  

